theme: minima
title: C'est La Vie
author: Muyun Cai
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:" You can edit this line in _config.yml. It will appear in your document head meta (for Google search results) and in your feed.xml site description.
  This site introduces Muyun's hobbies. 

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
